FROM postgres:11.16

ENV POSTGRES_USER flexberryuser
ENV POSTGRES_PASSWORD jhv
ENV POSTGRES_DB appdb

COPY 01-create-geo.sql /docker-entrypoint-initdb.d/
COPY 02-create-tables.sql /docker-entrypoint-initdb.d/
