FROM postgis/postgis:11-3.3-alpine

ENV POSTGRES_USER flexberryuser
ENV POSTGRES_PASSWORD jhv
ENV POSTGRES_DB appdb

COPY 00-create-gis-extension.sql /docker-entrypoint-initdb.d/
COPY 01-create-geo.sql /docker-entrypoint-initdb.d/
COPY 02-02-2023-create-favoritefearure-table.sql /docker-entrypoint-initdb.d/
COPY 02-create-tables.sql /docker-entrypoint-initdb.d/
COPY import_water_line.sql /docker-entrypoint-initdb.d/
COPY import_water_poly.sql /docker-entrypoint-initdb.d/
